baseURL = "https://WuSphere.github.io/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "relearn"

[params]
  customCSS = ["css/custom.css"]
  logo = "images/logo.png"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
identifier = "blog"
name = "ğŸ“– åšå®¢"
url = "/blog/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "ğŸš€ é¡¹ç›®"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "private"
name = "ğŸš€ ç§äºº"
url = "/private/"
weight = 3
