baseURL = "https://WuSphere.github.io/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "relearn"

[params]
  customCSS = ["css/custom.css"]
  logo = "images/logo.png"

[[menu.main]]
identifier = "blog"
name = "ğŸ“– åšå®¢"
url = "/blog/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "ğŸš€ é¡¹ç›®"
url = "/projects/"
weight = 2
